import { GenreType } from "../types";

export const Genres: GenreType[] = [
  { id: 1, name: "Action", isChecked: false },
  { id: 2, name: "Adventure", isChecked: false },
  { id: 5, name: "Avant Garde", isChecked: false },
  { id: 4, name: "Comedy", isChecked: false },
  { id: 6, name: "Demons", isChecked: false },
  { id: 8, name: "Drama", isChecked: false },
  { id: 9, name: "Ecchi", isChecked: false },
  { id: 10, name: "Fantasy", isChecked: false },
  { id: 11, name: "Game", isChecked: false },
  { id: 14, name: "Horror", isChecked: false },
  { id: 17, name: "Martial Arts", isChecked: false },
  { id: 18, name: "Mecha", isChecked: false },
  { id: 38, name: "Military", isChecked: false },
  { id: 19, name: "Music", isChecked: false },
  { id: 7, name: "Mystery", isChecked: false },
  { id: 20, name: "Parody", isChecked: false },
  { id: 39, name: "Police", isChecked: false },
  { id: 40, name: "Psychological", isChecked: false },
  { id: 22, name: "Romance", isChecked: false },
  { id: 21, name: "Samurai", isChecked: false },
  { id: 23, name: "School", isChecked: false },
  { id: 24, name: "SciFi", isChecked: false },
  { id: 36, name: "Slice of Life", isChecked: false },
  { id: 29, name: "Space", isChecked: false },
  { id: 30, name: "Sports", isChecked: false },
  { id: 37, name: "Supernatural", isChecked: false },
  { id: 31, name: "Super Power", isChecked: false },
  { id: 32, name: "Vampire", isChecked: false },
  { id: 43, name: "Josei", isChecked: false },
  { id: 15, name: "Kids", isChecked: false },
  { id: 42, name: "Seinen", isChecked: false },
  { id: 25, name: "Shoujo", isChecked: false },
  { id: 27, name: "Shounen", isChecked: false },
];
