import { ProducerType } from "../types";

export const Producers: ProducerType[] = [
  { id: 1286, name: "10Gauge" },
  { id: 713, name: "12 Diary Holders" },
  { id: 2137, name: "1IN" },
  { id: 1117, name: "1st PLACE" },
  { id: 1963, name: "1theK" },
  { id: 1807, name: "2:10 AM Animation" },
  { id: 1838, name: "33 Collective" },
  { id: 1079, name: "3xCube" },
  { id: 252, name: "4Kids Entertainment" },
  { id: 2264, name: "5 Inc." },
  { id: 1425, name: "5pb." },
  { id: 1185, name: "81 Produce" },
  { id: 441, name: "8bit" },
  { id: 56, name: "A-1 Pictures" },
  { id: 1733, name: "A-Craft" },
  { id: 171, name: "A-Line" },
  { id: 1257, name: "A-Real" },
  { id: 1635, name: "A-Sketch" },
  { id: 179, name: "A.C.G.T." },
  { id: 2290, name: "A3" },
  { id: 1500, name: "ABC Animation" },
  { id: 2016, name: "Abe Shuuji Jimusho" },
  { id: 1659, name: "AbemaTV" },
  { id: 667, name: "AC Create" },
  { id: 2272, name: "AC-Bu" },
  { id: 589, name: "Academy Productions" },
  { id: 420, name: "ACC Production" },
  { id: 2085, name: "Acca effe" },
  { id: 289, name: "ACiD FiLM" },
  { id: 60, name: "Actas" },
  { id: 121, name: "Active" },
  { id: 2101, name: "ADK" },
  { id: 2118, name: "ADK Emotions" },
  { id: 2232, name: "ADK Marketing Solutions" },
  { id: 1502, name: "Adores" },
  { id: 410, name: "Adult Source Media" },
  { id: 97, name: "ADV Films" },
  { id: 785, name: "Advance Syakujii" },
  { id: 1886, name: "Aeon Entertainment" },
  { id: 1580, name: "AG-ONE" },
  { id: 182, name: "Age" },
  { id: 1225, name: "Age Global Networks" },
  { id: 183, name: "Agent 21" },
  { id: 2294, name: "AHA Entertainment" },
  { id: 1041, name: "Ai Addiction" },
  { id: 184, name: "Ai ga areba Daijobu" },
  { id: 2068, name: "Ai Si Animation Studio" },
  { id: 48, name: "AIC" },
  { id: 88, name: "AIC ASTA" },
  { id: 436, name: "AIC Build" },
  { id: 1306, name: "AIC Classic" },
  { id: 805, name: "AIC Frontier" },
  { id: 292, name: "AIC PLUS+" },
  { id: 2255, name: "AIC Rights" },
  { id: 83, name: "AIC Spirits" },
  { id: 425, name: "AIC Takarazuka" },
  { id: 1083, name: "Aikikaku Center" },
  { id: 2359, name: "Aiko" },
  { id: 1246, name: "AIR AGENCY" },
  { id: 2362, name: "Aiti St." },
  { id: 30, name: "Ajia-Do" },
  { id: 1398, name: "Akabanten" },
  { id: 1707, name: "AKABEiSOFT2" },
  { id: 2034, name: "Akatsuki" },
  { id: 1373, name: "Akita Shoten" },
  { id: 809, name: "AKOM" },
  { id: 1999, name: "Albacrow" },
  { id: 172, name: "Alchemist" },
  { id: 1855, name: "Alchemy Bros." },
  { id: 2355, name: "Alfred Imageworks" },
  { id: 2346, name: "Alice Production" },
  { id: 2344, name: "All Products" },
  { id: 1161, name: "Allure" },
  { id: 1939, name: "Alpha Animation" },
  { id: 2170, name: "Alpha Group Co. Ltd." },
  { id: 2254, name: "Alpha Pictures" },
  { id: 2360, name: "Amarcord" },
  { id: 827, name: "Amber Film Works" },
  { id: 2221, name: "AMG Entertainment" },
  { id: 779, name: "AMG MUSIC" },
  { id: 408, name: "Amino" },
  { id: 1313, name: "Amuse" },
  { id: 380, name: "Amuse Pictures" },
  { id: 1401, name: "Amusement Media Academy" },
  { id: 878, name: "An DerCen" },
  { id: 2259, name: "AN Entertainment" },
  { id: 488, name: "Anchor Bay Films" },
  { id: 975, name: "Angelfish" },
  { id: 1951, name: "ANIDO FILM" },
  { id: 194, name: "ANIK" },
  { id: 298, name: "Anima" },
  { id: 1983, name: "Anima&amp;Co." },
  { id: 124, name: "Animac" },
  { id: 1243, name: "AniMan" },
  { id: 386, name: "Animaruya" },
  { id: 1906, name: "animate" },
  { id: 155, name: "animate Film" },
  { id: 1449, name: "Animatic" },
  { id: 326, name: "Animation 21" },
  { id: 929, name: "Animation Do" },
  { id: 2079, name: "Animation Lab Japan" },
  { id: 1861, name: "Animation Planet" },
  { id: 1952, name: "Animation Staff Room" },
  { id: 1528, name: "Animatsu Entertainment" },
  { id: 140, name: "Animax" },
  { id: 1463, name: "Anime Antenna Iinkai" },
  { id: 1723, name: "Anime Beans" },
  { id: 1510, name: "Anime Consortium Japan" },
  { id: 1990, name: "Anime Friend" },
  { id: 277, name: "Anime Midstream" },
  { id: 971, name: "Anime R" },
  { id: 310, name: "AnimEigo" },
  { id: 17, name: "Aniplex" },
  { id: 493, name: "Aniplex of America" },
  { id: 919, name: "Ankama" },
  { id: 1897, name: "Ankama Animations" },
  { id: 583, name: "Annapuru" },
  { id: 1949, name: "Anon Pictures" },
  { id: 521, name: "Anpro" },
  { id: 2156, name: "Aoi Studio" },
  { id: 1962, name: "AOMG" },
  { id: 1802, name: "Aoni Entertainment" },
  { id: 1720, name: "Aoni Production" },
  { id: 1883, name: "APDREAM" },
  { id: 747, name: "Apollon" },
  { id: 77, name: "APPP" },
  { id: 2071, name: "AQUA ARIS" },
  { id: 1801, name: "Aquamarine" },
  { id: 1329, name: "AQUAPLUS" },
  { id: 1445, name: "Arcs Create" },
  { id: 1282, name: "Arcturus" },
  { id: 2265, name: "ARECT" },
  { id: 2020, name: "Ark" },
  { id: 1986, name: "arma bianca" },
  { id: 297, name: "Armor" },
  { id: 38, name: "Arms" },
  { id: 585, name: "Arplants" },
  { id: 1912, name: "Arquebuse" },
  { id: 1900, name: "Artist Management Office" },
  { id: 8, name: "Artland" },
  { id: 72, name: "Artmic" },
  { id: 2261, name: "Arts Magic" },
  { id: 1874, name: "Arvo Animation" },
  { id: 1415, name: "Asahi Broadcasting" },
  { id: 406, name: "Asahi Production" },
  { id: 1318, name: "Asahi Shimbun" },
  { id: 142, name: "Asatsu DK" },
  { id: 473, name: "Ascension" },
  { id: 681, name: "ASCII Media Works" },
  { id: 1816, name: "Asgard" },
  { id: 242, name: "Ashi Production" },
  { id: 1885, name: "Ashisuto" },
  { id: 1021, name: "ASIA Documentary Productions" },
  { id: 2048, name: "ASK Animation Studio" },
  { id: 517, name: "Asmik Ace" },
  { id: 163, name: "asread." },
  { id: 1271, name: "Assez Finaud Fabric" },
  { id: 1399, name: "Asura Film" },
  { id: 579, name: "AT-2" },
  { id: 238, name: "AT-X" },
  { id: 1175, name: "Atelier Musa" },
  { id: 2298, name: "AtelierPontdarc" },
  { id: 344, name: "Atlus" },
  { id: 1009, name: "Aubec" },
  { id: 1878, name: "Audio Graphics Institute" },
  { id: 645, name: "Audio Highs" },
  { id: 1506, name: "Audio Planning U" },
  { id: 1461, name: "Audio Tanaka" },
  { id: 1867, name: "Aurum Production" },
  { id: 482, name: "Automatic Flowers Studio" },
  { id: 379, name: "Avaco Creative Studios" },
  { id: 52, name: "Avex Entertainment" },
  { id: 1284, name: "Avex Pictures" },
  { id: 2105, name: "Avex Technologies" },
  { id: 1299, name: "AXsiZ" },
  { id: 907, name: "AYCO" },
  { id: 1694, name: "AZ Creative" },
  { id: 1191, name: "Azeta Pictures" },
  { id: 1429, name: "Azumaker" },
  { id: 1462, name: "B&amp;T" },
  { id: 1350, name: "B.CMAY PICTURES" },
  { id: 1984, name: "Bakken Record" },
  { id: 1610, name: "Baku Enterprise" },
  { id: 230, name: "Bandai" },
  { id: 1588, name: "Bandai Channel" },
  { id: 233, name: "Bandai Entertainment" },
  { id: 1840, name: "Bandai Namco Arts" },
  { id: 1233, name: "Bandai Namco Entertainment" },
  { id: 1097, name: "Bandai Namco Games" },
  { id: 687, name: "Bandai Namco Live Creative" },
  { id: 2006, name: "Bandai Namco Online" },
  { id: 1258, name: "Bandai Namco Pictures" },
  { id: 1544, name: "Bandai Namco Rights Marketing" },
  { id: 1992, name: "Bandai Spirits" },
  { id: 23, name: "Bandai Visual" },
  { id: 1466, name: "Bandai Visual USA" },
  { id: 1121, name: "Banpresto" },
  { id: 961, name: "Baramiri" },
  { id: 271, name: "Barnum Studio" },
  { id: 1139, name: "BEAM Entertainment" },
  { id: 59, name: "Beat Frog" },
  { id: 2357, name: "BeDream" },
  { id: 322, name: "Bee Media" },
  { id: 5, name: "Bee Train" },
  { id: 1029, name: "BeeWorks" },
  { id: 1465, name: "Beijing Enlight Pictures" },
  { id: 1456, name: "Beijing Huihuang Animation Company" },
  { id: 2120, name: "Beijing IMMG" },
  { id: 1706, name: "Beijing Rocen Digital" },
  { id: 458, name: "Beijing Sharaku Art" },
  { id: 1341, name: "Beijing Sunchime Happy Culture Company" },
  { id: 1285, name: "Being" },
  { id: 1043, name: "Benesse Corporation" },
  { id: 2082, name: "Benlai Pictures" },
  { id: 89, name: "BeSTACK" },
  { id: 1584, name: "Beyond C." },
  { id: 2083, name: "Bianyue Culture " },
  { id: 2325, name: "Bibury Animation CG" },
  { id: 1722, name: "Bibury Animation Studios" },
  { id: 1157, name: "Big Bang" },
  { id: 351, name: "Big West" },
  { id: 2358, name: "Big Wing" },
  { id: 1711, name: "BIGFACE" },
  { id: 1980, name: "BigFireBird Animation" },
  { id: 789, name: "BIGLOBE" },
  { id: 1414, name: "bilibili" },
  { id: 1432, name: "Bishop" },
  { id: 2074, name: "Bit grooove promotion" },
  { id: 1869, name: "Bit Promotion" },
  { id: 1326, name: "Bitgang" },
  { id: 2197, name: "blackflag" },
  { id: 1547, name: "Blade" },
  { id: 445, name: "Bliss Pictures" },
  { id: 2144, name: "BloomZ" },
  { id: 1385, name: "Blue Cat" },
  { id: 387, name: "Blue Eyes" },
  { id: 174, name: "Blue Impact" },
  { id: 157, name: "BMG Japan" },
  { id: 2049, name: "BOMB! CUTE! BOMB!" },
  { id: 4, name: "Bones" },
  { id: 2092, name: "BookLive" },
  { id: 981, name: "BOOTLEG" },
  { id: 2301, name: "Borutong" },
  { id: 1487, name: "Bouncy" },
  { id: 1811, name: "Boyan Pictures" },
  { id: 112, name: "Brain's Base" },
  { id: 2238, name: "Brave group" },
  { id: 1745, name: "Brave Hearts" },
  { id: 1093, name: "BreakBottle" },
  { id: 397, name: "Bridge" },
  { id: 1887, name: "Brio Animation" },
  { id: 116, name: "Broccoli" },
  { id: 2185, name: "BS Asahi" },
  { id: 843, name: "BS Fuji" },
  { id: 1469, name: "BS Japan" },
  { id: 1680, name: "BS NTV" },
  { id: 214, name: "BS-i" },
  { id: 693, name: "BS-TBS" },
  { id: 1416, name: "BS11" },
  { id: 1279, name: "Buemon" },
  { id: 2191, name: "BUILD DREAM" },
  { id: 1579, name: "Bulls Eye" },
  { id: 1619, name: "Bungeishunjuu" },
  { id: 775, name: "Bushiroad" },
  { id: 2228, name: "Bushiroad Move" },
  { id: 1634, name: "Bushiroad Music" },
  { id: 2110, name: "Buzz Wave" },
  { id: 491, name: "Byakuya Shobo" },
  { id: 2055, name: "BYMENT" },
  { id: 1497, name: "C &amp; I entertainment" },
  { id: 2225, name: "C-one" },
  { id: 1075, name: "C-Station" },
  { id: 605, name: "C2C" },
  { id: 1901, name: "CA-Cygames Anime Fund" },
  { id: 2323, name: "Cafe de Jeilhouse" },
  { id: 1063, name: "Calf Studio" },
  { id: 609, name: "Cammot" },
  { id: 2134, name: "CANDY BOX" },
  { id: 240, name: "Capcom" },
  { id: 933, name: "Carp Studio" },
  { id: 328, name: "Casio Entertainment" },
  { id: 2231, name: "CBC Radio" },
  { id: 146, name: "CBC Television" },
  { id: 1480, name: "CBS" },
  { id: 1301, name: "CCTV Animation" },
  { id: 2087, name: "CEKAI" },
  { id: 1922, name: "Celsys" },
  { id: 284, name: "Central Park Media" },
  { id: 1808, name: "CG Year" },
  { id: 1976, name: "CGCG Studio" },
  { id: 2155, name: "CHANCE iN" },
  { id: 462, name: "Chaos Project" },
  { id: 665, name: "chara-ani.com" },
  { id: 856, name: "Charaction" },
  { id: 130, name: "CherryLips" },
  { id: 1628, name: "Chiba TV" },
  { id: 402, name: "ChiChinoya" },
  { id: 1407, name: "Children's Playground Entertainment" },
  { id: 1710, name: "China Animation Characters" },
  { id: 2119, name: "China Film Animation" },
  { id: 1728, name: "China Literature Limited" },
  { id: 1546, name: "Chippai" },
  { id: 1639, name: "Chiptune" },
  { id: 2223, name: "Christmas Holly" },
  { id: 1288, name: "Chrono Gear Creative" },
  { id: 401, name: "ChuChu" },
  { id: 1336, name: "Chugai Mining" },
  { id: 1781, name: "Chukong Technologies" },
  { id: 1701, name: "Chukyo TV Broadcasting" },
  { id: 353, name: "Chungeorahm Film" },
  { id: 1405, name: "Chuubu Nihon Kyouei" },
  { id: 1586, name: "CIC" },
  { id: 1484, name: "Cinelicious Pics" },
  { id: 886, name: "Cinema Tohoku" },
  { id: 1384, name: "CinePix" },
  { id: 1642, name: "Circle Tribute" },
  { id: 1876, name: "CLAP" },
  { id: 1395, name: "Clarion" },
  { id: 2088, name: "Cloud22" },
  { id: 1835, name: "CloverWorks" },
  { id: 2216, name: "CMAY Animation" },
  { id: 995, name: "Coamix" },
  { id: 1460, name: "Coastline Animation Studio" },
  { id: 1675, name: "Cocoro Free" },
  { id: 325, name: "Code" },
  { id: 519, name: "Collaboration Works" },
  { id: 1613, name: "COLOPL" },
  { id: 1831, name: "Colored Pencil Animation" },
  { id: 2002, name: "Comic Animation" },
  { id: 1207, name: "Comic Umenohone" },
  { id: 1481, name: "comico" },
  { id: 1902, name: "COMICSMART" },
  { id: 291, name: "CoMix Wave Films" },
  { id: 1926, name: "Company AZA" },
  { id: 2159, name: "Composition Inc." },
  { id: 1141, name: "Comstock, Ltd." },
  { id: 2066, name: "Congzhuo Animation" },
  { id: 957, name: "Connect" },
  { id: 1554, name: "Contents Seed" },
  { id: 451, name: "Cookie Jar Entertainment" },
  { id: 1535, name: "Coolism Productions" },
  { id: 745, name: "Cosmic Ray" },
  { id: 1085, name: "Cosmos" },
  { id: 619, name: "Cospa" },
  { id: 821, name: "Cotton Doll" },
  { id: 1357, name: "Craftar Studios" },
  { id: 356, name: "Cranberry" },
  { id: 987, name: "Creative Bridge" },
  { id: 1322, name: "Creative Power Entertaining" },
  { id: 1662, name: "Creators Dot Com" },
  { id: 1195, name: "Creators in Pack" },
  { id: 1961, name: "Creatures Inc." },
  { id: 1657, name: "Creek &amp; River" },
  { id: 1490, name: "CREi" },
  { id: 965, name: "Crimson Star Media" },
  { id: 296, name: "Critical Mass Video" },
  { id: 1788, name: "Cromea" },
  { id: 551, name: "Crossphere" },
  { id: 2077, name: "Crown Records" },
  { id: 1468, name: "Crunchyroll" },
  { id: 1784, name: "Crunchyroll SC Anime Fund" },
  { id: 2236, name: "CTW" },
  { id: 1795, name: "CUCURI" },
  { id: 2017, name: "Culture Entertainment" },
  { id: 2190, name: "Culture Publishers" },
  { id: 2340, name: "Cutie Bee" },
  { id: 1422, name: "CyberAgent" },
  { id: 231, name: "CyberConnect2" },
  { id: 923, name: "CyberStep" },
  { id: 1099, name: "Cyclone Graphics" },
  { id: 1587, name: "Cygames" },
  { id: 1893, name: "CygamesPictures" },
  { id: 1753, name: "D &amp; D Pictures" },
  { id: 164, name: "d-rights" },
  { id: 1819, name: "D-techno" },
  { id: 567, name: "D.A.S.T." },
  { id: 1791, name: "D.N. Dream Partners" },
  { id: 244, name: "D3" },
  { id: 1940, name: "Da Huoniao Donghua" },
  { id: 228, name: "Daewon Media" },
  { id: 1549, name: "Dai Nippon Printing" },
  { id: 1512, name: "Dai-Ichi Douga" },
  { id: 278, name: "Daiei" },
  { id: 1632, name: "Daiichi Shokai" },
  { id: 1215, name: "Daiichikosho" },
  { id: 983, name: "Daiko" },
  { id: 1848, name: "Dancing CG Studio" },
  { id: 1111, name: "DandeLion Animation Studio" },
  { id: 1879, name: "Dangun Pictures" },
  { id: 1361, name: "Darts" },
  { id: 1729, name: "Datam Polystar" },
  { id: 2319, name: "Datama Film" },
  { id: 39, name: "Daume" },
  { id: 287, name: "David Production" },
  { id: 2241, name: "Dawn Animation" },
  { id: 315, name: "DAX Production" },
  { id: 2046, name: "Dazzling Star" },
  { id: 1803, name: "Dear Stage inc." },
  { id: 1328, name: "Decovocal" },
  { id: 1965, name: "Deho Gallery" },
  { id: 711, name: "Delfi Sound" },
  { id: 2247, name: "Delight Animation" },
  { id: 2008, name: "Delightworks" },
  { id: 1576, name: "DeNA" },
  { id: 53, name: "Dentsu" },
  { id: 1251, name: "Dentsu Eigasha Tokyo" },
  { id: 791, name: "Dentsu Entertainment USA" },
  { id: 2131, name: "Dentsu Meitetsu Communications" },
  { id: 1606, name: "Dentsu Razorfish" },
  { id: 1607, name: "Dentsu Tec" },
  { id: 1570, name: "Design Factory" },
  { id: 269, name: "DiC Entertainment" },
  { id: 486, name: "Digital Frontier" },
  { id: 466, name: "Digital Media Lab" },
  { id: 1796, name: "Digital Network Animation" },
  { id: 206, name: "Digital Works" },
  { id: 1439, name: "Digiturbo" },
  { id: 51, name: "Diomedéa" },
  { id: 324, name: "Directions" },
  { id: 467, name: "Discotek Media" },
  { id: 294, name: "Discovery" },
  { id: 1039, name: "DIVE II Entertainment" },
  { id: 2124, name: "Diwphalanx Records" },
  { id: 1736, name: "DJI" },
  { id: 2133, name: "Djinn Power" },
  { id: 276, name: "DLE" },
  { id: 2139, name: "DMM Music" },
  { id: 1671, name: "DMM pictures" },
  { id: 1542, name: "DMM.com" },
  { id: 2199, name: "DMM.com Labo" },
  { id: 1673, name: "DMM.futureworks" },
  { id: 1334, name: "Docomo Anime Store" },
  { id: 95, name: "Doga Kobo" },
  { id: 479, name: "DOGA Productions" },
  { id: 1911, name: "Dokidoki Factory" },
  { id: 1380, name: "domerica" },
  { id: 1025, name: "Dongwoo A&amp;E" },
  { id: 1513, name: "Dongyang Animation" },
  { id: 1658, name: "Donuts" },
  { id: 1575, name: "DR Movie" },
  { id: 2275, name: "Drawing and Manual" },
  { id: 2056, name: "DRAWIZ" },
  { id: 615, name: "Dream Creation" },
  { id: 2317, name: "Dream Entertainment" },
  { id: 399, name: "Dream Force" },
  { id: 2090, name: "Dream Shift" },
  { id: 1475, name: "DreamWorks" },
  { id: 1799, name: "Drecom" },
  { id: 1967, name: "Drive" },
  { id: 1661, name: "drop" },
  { id: 1609, name: "Duckbill Entertainment" },
  { id: 1856, name: "dugout" },
  { id: 2158, name: "Durufix" },
  { id: 715, name: "Dwango" },
  { id: 663, name: "Dwango Music Entertainment" },
  { id: 1133, name: "dwarf" },
  { id: 921, name: "Dynamic Planning" },
  { id: 1263, name: "Dynamo Pictures" },
  { id: 154, name: "E&amp;G Films" },
  { id: 1689, name: "e-notion" },
  { id: 2029, name: "Earth Design Works" },
  { id: 925, name: "Earth Star Entertainment" },
  { id: 1633, name: "eBooK Initiative Japan" },
  { id: 1427, name: "EBS" },
  { id: 258, name: "Echo" },
  { id: 1522, name: "Echoes" },
  { id: 1351, name: "EDGE" },
  { id: 593, name: "Egg" },
  { id: 1444, name: "Egg Firm" },
  { id: 1486, name: "eigoMANGA" },
  { id: 191, name: "Eiken" },
  { id: 1794, name: "EKACHI EPILKA" },
  { id: 2151, name: "Ekakiya" },
  { id: 1433, name: "Ekura Animal" },
  { id: 419, name: "ElectromagneticWave" },
  { id: 531, name: "Eleven Arts" },
  { id: 2242, name: "ELF-IN" },
  { id: 815, name: "EMI" },
  { id: 1530, name: "Emon" },
  { id: 1264, name: "EMT Squared" },
  { id: 354, name: "Encourage Films" },
  { id: 1974, name: "ENGI" },
  { id: 1991, name: "Enishiya" },
  { id: 2041, name: "Enjin Productions" },
  { id: 311, name: "Enoki Films" },
  { id: 1330, name: "ensky" },
  { id: 2107, name: "entama" },
  { id: 392, name: "Enterbrain" },
  { id: 1824, name: "Epicross" },
  { id: 393, name: "Epoch" },
  { id: 2038, name: "Eswood" },
  { id: 2114, name: "Ether Kitten" },
  { id: 1241, name: "Evil Line Records" },
  { id: 1598, name: "Exa International" },
  { id: 1594, name: "Exit Tunes" },
  { id: 2297, name: "EXNOA" },
  { id: 759, name: "Eye Move" },
  { id: 1864, name: "Ezόla" },
  { id: 1289, name: "F.M.F" },
  { id: 2102, name: "f4samurai" },
  { id: 2128, name: "FABTONE" },
  { id: 515, name: "Fairy Dust" },
  { id: 1332, name: "famima.com" },
  { id: 2094, name: "Fan Company" },
  { id: 2153, name: "FanFan Inc." },
  { id: 866, name: "Fanworks" },
  { id: 2121, name: "FBC" },
  { id: 91, name: "feel." },
  { id: 2021, name: "Felicity" },
  { id: 1440, name: "Felix Film" },
  { id: 699, name: "feng" },
  { id: 2076, name: "Fenz" },
  { id: 1358, name: "Fields" },
  { id: 825, name: "Fifth Avenue" },
  { id: 362, name: "Film Workshop" },
  { id: 426, name: "Filmlink International" },
  { id: 2033, name: "FILMONY" },
  { id: 2179, name: "FIREBUG" },
  { id: 267, name: "Five Ways" },
  { id: 2249, name: "FLAGSHIP LINE" },
  { id: 2067, name: "Flat Studio" },
  { id: 1163, name: "Flatiron Film Company" },
  { id: 1531, name: "Flavors Soft" },
  { id: 874, name: "Flex Comix" },
  { id: 464, name: "flying DOG" },
  { id: 2123, name: "foodunited." },
  { id: 1423, name: "Forecast Communications" },
  { id: 1135, name: "FOREST Hunting One" },
  { id: 2312, name: "Fosun Entertainment Japan" },
  { id: 285, name: "Four Some" },
  { id: 1307, name: "Free-Will" },
  { id: 1389, name: "Frencel" },
  { id: 1881, name: "Friendly Land" },
  { id: 69, name: "Front Line" },
  { id: 2202, name: "Front Wing" },
  { id: 61, name: "Frontier Works" },
  { id: 1556, name: "Fuji Creative" },
  { id: 169, name: "Fuji TV" },
  { id: 509, name: "Fuji Video" },
  { id: 1483, name: "Fuji&amp;gumi Games" },
  { id: 1315, name: "Fujiko F. Fujio Pro" },
  { id: 1664, name: "Fujimi Shobo" },
  { id: 1822, name: "Fujio Production" },
  { id: 769, name: "Fujipacific Music" },
  { id: 1714, name: "Fujishouji" },
  { id: 1656, name: "FUJIYAMA PROJECT JAPAN" },
  { id: 1703, name: "Fukuoka Broadcasting System" },
  { id: 2305, name: "Fukushima Gaina" },
  { id: 102, name: "Funimation" },
  { id: 1590, name: "FuRyu" },
  { id: 1377, name: "Futabasha" },
  { id: 2237, name: "FUTURE LEAP " },
  { id: 340, name: "Future Planet" },
  { id: 2152, name: "G holdings" },
  { id: 131, name: "G&amp;G Entertainment" },
  { id: 1837, name: "G-angle" },
  { id: 1369, name: "G-Lam" },
  { id: 876, name: "G-mode" },
  { id: 470, name: "GAGA" },
  { id: 1314, name: "Gaina" },
  { id: 6, name: "Gainax" },
  { id: 1971, name: "Gainax Kyoto" },
  { id: 198, name: "Gakken" },
  { id: 1091, name: "Gakken Eigakyoku" },
  { id: 36, name: "Gallop" },
  { id: 2226, name: "Gambit" },
  { id: 1895, name: "Gamegate" },
  { id: 721, name: "GANSIS" },
  { id: 2175, name: "Garden Culture" },
  { id: 1419, name: "GARDEN LODGE" },
  { id: 400, name: "Gathering" },
  { id: 42, name: "GDH" },
  { id: 1857, name: "GEEK TOYS" },
  { id: 1524, name: "Geidai Animation" },
  { id: 1177, name: "Geijutsu Eigasha" },
  { id: 1381, name: "GEMBA" },
  { id: 189, name: "GEN Productions" },
  { id: 1526, name: "Gen'ei" },
  { id: 79, name: "Genco" },
  { id: 1105, name: "Gendai Production" },
  { id: 1459, name: "Geneon Entertainment USA" },
  { id: 31, name: "Geneon Universal Entertainment" },
  { id: 2026, name: "Genie Music" },
  { id: 1393, name: "Geno Studio" },
  { id: 282, name: "Gentosha Comics" },
  { id: 2299, name: "GIFTanimation" },
  { id: 2086, name: "Giga Production" },
  { id: 1636, name: "Gigno Systems" },
  { id: 880, name: "gimik" },
  { id: 176, name: "Ginga Ya" },
  { id: 783, name: "GKIDS" },
  { id: 793, name: "Glams" },
  { id: 2095, name: "Global Solutions" },
  { id: 1255, name: "Glovision" },
  { id: 302, name: "GODxDOG Production" },
  { id: 1925, name: "GoGo Visual Planning" },
  { id: 309, name: "GoHands" },
  { id: 1721, name: "Gold Bear" },
  { id: 3, name: "Gonzo" },
  { id: 1261, name: "Good Smile Company" },
  { id: 1899, name: "Good Smile Film" },
  { id: 2127, name: "GOON TRAX" },
  { id: 2115, name: "Gosay Studio" },
  { id: 1923, name: "Graduate School of Film Producing" },
  { id: 2099, name: "GRANTdesign" },
  { id: 894, name: "Graphinica" },
  { id: 378, name: "Grasshoppa!" },
  { id: 1815, name: "GREE" },
  { id: 2289, name: "GREE Entertainment" },
  { id: 152, name: "Green Bunny" },
  { id: 1959, name: "Green Monster Team" },
  { id: 1743, name: "Greenwood" },
  { id: 1832, name: "GRIZZLY" },
  { id: 1866, name: "Grom" },
  { id: 1254, name: "Grooove" },
  { id: 86, name: "Group TAC" },
  { id: 391, name: "Grouper Productions" },
  { id: 1845, name: "Guton Animation Studio" },
  { id: 1602, name: "GYAO!" },
  { id: 2311, name: "Gyorai Eizo Inc." },
  { id: 1674, name: "Gzbrain" },
  { id: 2192, name: "Hai An Xian Donghua Gongzuo Shi" },
  { id: 649, name: "Hakoniwa Academy Student Council" },
  { id: 1563, name: "Hakuhodo" },
  { id: 1488, name: "Hakuhodo DY Media Partners" },
  { id: 1333, name: "Hakuhodo DY Music &amp; Pictures" },
  { id: 148, name: "Hakusensha" },
  { id: 34, name: "Hal Film Maker" },
  { id: 213, name: "Half H.P Studio" },
  { id: 2364, name: "Hanjin Animation" },
  { id: 1325, name: "Haoliners Animation League" },
  { id: 1933, name: "Happinet" },
  { id: 787, name: "Happinet Pictures" },
  { id: 1793, name: "Happy Elements" },
  { id: 1256, name: "Harappa" },
  { id: 2278, name: "Harmony Gold" },
  { id: 465, name: "Hasbro" },
  { id: 1946, name: "Hawkeye" },
  { id: 2181, name: "Hayakawa Shobou" },
  { id: 2147, name: "Heart Company" },
  { id: 1217, name: "HeART-BIT" },
  { id: 367, name: "Heewon Entertainment" },
  { id: 2035, name: "Heiwa" },
  { id: 1769, name: "helo.inc" },
  { id: 447, name: "Hero Communication" },
  { id: 1503, name: "Heroz" },
  { id: 1917, name: "Hexagon Pictures" },
  { id: 2078, name: "HIDEHOMARE" },
  { id: 527, name: "Higa Brothers Production" },
  { id: 1904, name: "High Kick Entertainment" },
  { id: 1539, name: "Highlights Entertainment" },
  { id: 2138, name: "Hikari TV" },
  { id: 138, name: "Himajin Planning" },
  { id: 1019, name: "Himeyuri Alumnae Incorporated Foundation" },
  { id: 1716, name: "Hipland Music Corporation" },
  { id: 1994, name: "Hirameki International" },
  { id: 1464, name: "Hiro Media" },
  { id: 1310, name: "Hiroshi Planning" },
  { id: 1702, name: "Hiroshima Television" },
  { id: 1457, name: "Hisashishi Videos" },
  { id: 2227, name: "HJ Holdings" },
  { id: 2116, name: "HOBBY BASE Yellow Submarine" },
  { id: 547, name: "Hobby Japan" },
  { id: 1347, name: "Hobi Animation" },
  { id: 1495, name: "Hobibox" },
  { id: 2100, name: "Hochi Shimbun" },
  { id: 1219, name: "Hokkaido Azmacy" },
  { id: 1221, name: "Hokkaido Cultural Broadcasting" },
  { id: 2167, name: "Hololive Production" },
  { id: 1360, name: "Hoods Drifters Studio" },
  { id: 346, name: "Hoods Entertainment" },
  { id: 492, name: "Horannabi" },
  { id: 2285, name: "Horgos Coloroom Pictures Co., Ltd." },
  { id: 134, name: "HoriPro" },
  { id: 2015, name: "HoriPro International" },
  { id: 2097, name: "HORNETS" },
  { id: 991, name: "Hoso Seisaku Doga" },
  { id: 268, name: "Hot Bear" },
  { id: 723, name: "Hotline" },
  { id: 1972, name: "HOTZIPANG" },
  { id: 797, name: "Houbunsha" },
  { id: 1276, name: "HS Pictures Studio" },
  { id: 1695, name: "Hulu" },
  { id: 1766, name: "Husio Studio" },
  { id: 1235, name: "I was a Ballerina" },
  { id: 1605, name: "I Will" },
  { id: 1681, name: "I'm Enterprise" },
  { id: 389, name: "I-move" },
  { id: 898, name: "I.Gzwei" },
  { id: 375, name: "I.Toon" },
  { id: 1331, name: "i0+" },
  { id: 2093, name: "ibis Capital Partners" },
  { id: 2001, name: "Ichigo Animation" },
  { id: 1582, name: "Ichijinsha" },
  { id: 193, name: "Idea Factory" },
  { id: 1943, name: "Idol" },
  { id: 1767, name: "iDRAGONS Creative Studio" },
  { id: 2347, name: "IKK Room" },
  { id: 1169, name: "ILCA" },
  { id: 2262, name: "Illumitoon Entertainment" },
  { id: 1713, name: "Ima Group" },
  { id: 1527, name: "Image House" },
  { id: 1153, name: "Image Kei" },
  { id: 255, name: "Imagi" },
  { id: 170, name: "Imagica" },
  { id: 1812, name: "Imagica Imageworks" },
  { id: 1903, name: "IMAGICA Lab." },
  { id: 1277, name: "Imagica West" },
  { id: 75, name: "Imagin" },
  { id: 2263, name: "ImaginAsian Entertainment" },
  { id: 2135, name: "Imagine" },
  { id: 1690, name: "Imagineer" },
  { id: 1862, name: "Include P.D." },
  { id: 1731, name: "INCS toenter" },
  { id: 331, name: "Indeprox" },
  { id: 870, name: "Index" },
  { id: 799, name: "indigo line" },
  { id: 2248, name: "Indivision" },
  { id: 1386, name: "Infinite" },
  { id: 469, name: "ING" },
  { id: 357, name: "Innocent Grey" },
  { id: 421, name: "International Digital Artist" },
  { id: 2320, name: "Inugoya" },
  { id: 1806, name: "iQIYI" },
  { id: 2198, name: "Irawias" },
  { id: 475, name: "Ishikawa Pro" },
  { id: 1437, name: "Ishimori Entertainment" },
  { id: 1561, name: "Ishimori Pro" },
  { id: 1353, name: "Issen" },
  { id: 2104, name: "it's" },
  { id: 349, name: "Itasca Studio" },
  { id: 941, name: "Iwatobi High School Swimming Club" },
  { id: 601, name: "ixtl" },
  { id: 370, name: "Iyasakadou Film" },
  { id: 7, name: "J.C.Staff" },
  { id: 222, name: "Jade Animation" },
  { id: 257, name: "Jam" },
  { id: 342, name: "Japan Home Video" },
  { id: 1629, name: "Japan Sleeve" },
  { id: 1545, name: "Japan Taps" },
  { id: 1037, name: "Japan Vistec" },
  { id: 2180, name: "Japan Volleyball Association" },
  { id: 573, name: "JapanAnime" },
  { id: 1826, name: "Jay Zone Comic" },
  { id: 1435, name: "JCF" },
  { id: 2291, name: "jeux d'eau" },
  { id: 2210, name: "Jichitai Anime" },
  { id: 1663, name: "Jidaigeki Channel" },
  { id: 1517, name: "Jinnan Studio" },
  { id: 444, name: "Jinnis Animation Studios" },
  { id: 2081, name: "JJJOY Animation Studios" },
  { id: 336, name: "JM Animation" },
  { id: 2363, name: "JOF" },
  { id: 1320, name: "Joker Films" },
  { id: 1646, name: "JP Room" },
  { id: 1501, name: "JR East Marketing &amp; Communications" },
  { id: 1538, name: "JTB Entertainment" },
  { id: 1989, name: "JTB Next Creation" },
  { id: 360, name: "Jules Bass" },
  { id: 755, name: "Jumondo" },
  { id: 1851, name: "Jumonji" },
  { id: 1645, name: "Just Production" },
  { id: 1735, name: "JY Animation" },
  { id: 1269, name: "K-Factory" },
  { id: 2061, name: "Kaca Entertainment" },
  { id: 432, name: "Kachidoki Studio" },
  { id: 1696, name: "Kadokawa" },
  { id: 1916, name: "Kadokawa Animation" },
  { id: 685, name: "Kadokawa Contents Gate" },
  { id: 1709, name: "Kadokawa Daiei Studio" },
  { id: 1738, name: "Kadokawa Games" },
  { id: 1913, name: "Kadokawa Haruki Corporation" },
  { id: 1540, name: "Kadokawa Media (Taiwan)" },
  { id: 1551, name: "Kadokawa Media House" },
  { id: 352, name: "Kadokawa Pictures Japan" },
  { id: 262, name: "Kadokawa Pictures USA" },
  { id: 113, name: "Kadokawa Shoten" },
  { id: 259, name: "Kaeruotoko Shokai" },
  { id: 525, name: "KAGAYA Studio" },
  { id: 2024, name: "Kaibutsu" },
  { id: 1649, name: "Kakao Japan" },
  { id: 437, name: "Kamikaze Douga" },
  { id: 1592, name: "Kamio Japan" },
  { id: 2309, name: "Kamitsubaki Studio" },
  { id: 330, name: "Kanaban Graphics" },
  { id: 2072, name: "Kanade Creative" },
  { id: 288, name: "Kaname Productions" },
  { id: 1677, name: "Kanetsu Investment" },
  { id: 1494, name: "Kanon Sound" },
  { id: 1412, name: "Kansai Telecasting" },
  { id: 2350, name: "Kantou Douga Kai" },
  { id: 890, name: "Karaku" },
  { id: 1668, name: "Karasfilms" },
  { id: 1947, name: "Kate Arrow" },
  { id: 575, name: "Katsudou-manga-kan" },
  { id: 1740, name: "Kawade Shobo Shinsha" },
  { id: 348, name: "Kawamoto Productions" },
  { id: 848, name: "Kazami Gakuen Koushiki Douga-bu" },
  { id: 1368, name: "Kazuki Production" },
  { id: 411, name: "KBS" },
  { id: 1697, name: "KDDI" },
  { id: 2183, name: "Keica" },
  { id: 1621, name: "Keisei Electric Railway" },
  { id: 1790, name: "KEN ON" },
  { id: 850, name: "Kenji Studio" },
  { id: 283, name: "KENMedia" },
  { id: 1704, name: "Ketchup Entertainment" },
  { id: 1239, name: "KeyEast" },
  { id: 47, name: "Khara" },
  { id: 1755, name: "Ki/oon Music" },
  { id: 158, name: "Kids Station" },
  { id: 290, name: "Kinema Citrus" },
  { id: 1159, name: "King Bee" },
  { id: 1344, name: "King Records" },
  { id: 477, name: "Kino Production" },
  { id: 1653, name: "Kinoshita Group Holdings" },
  { id: 1346, name: "Kinoshita Koumuten" },
  { id: 2149, name: "Kinoshita Management" },
  { id: 1679, name: "Kinyosha" },
  { id: 2256, name: "Kitty Film Mitaka Studio" },
  { id: 99, name: "Kitty Films" },
  { id: 321, name: "Kitty Media" },
  { id: 727, name: "Kiyosumi High School Mahjong Club" },
  { id: 1770, name: "KIZAWA Studio" },
  { id: 1773, name: "KJJ Animation" },
  { id: 2348, name: "KKC Animation Production" },
  { id: 1787, name: "KLab" },
  { id: 460, name: "KlockWorx" },
  { id: 383, name: "KMMJ Studios" },
  { id: 535, name: "Knack Animation" },
  { id: 452, name: "Knack Productions" },
  { id: 1559, name: "Kobunsha" },
  { id: 159, name: "Kodansha" },
  { id: 241, name: "Koei" },
  { id: 1498, name: "Koei Tecmo Games" },
  { id: 275, name: "Kojiro Shishido Animation Works" },
  { id: 281, name: "Kokusai Eigasha" },
  { id: 85, name: "Konami" },
  { id: 1470, name: "Konami Digital Entertainment" },
  { id: 1291, name: "KOO-KI" },
  { id: 1942, name: "Korean Academy of Film Arts" },
  { id: 1719, name: "Kotobukiya" },
  { id: 50, name: "KSS" },
  { id: 1640, name: "Kujou-kun no Bonnou wo Mimamoru-kai" },
  { id: 2356, name: "Kung Fu Frog Animation" },
  { id: 377, name: "Kuri Jikken Manga Kobo" },
  { id: 1001, name: "Kyodo Eiga" },
  { id: 1411, name: "Kyoraku Industrial Holdings" },
  { id: 2, name: "Kyoto Animation" },
  { id: 833, name: "Kyotoma" },
  { id: 1057, name: "Kyowa Film" },
  { id: 2053, name: "l-a-unch・BOX" },
  { id: 1199, name: "L." },
  { id: 1101, name: "Lambert" },
  { id: 563, name: "LandQ studios" },
  { id: 301, name: "Langmaor" },
  { id: 104, name: "Lantis" },
  { id: 1828, name: "Lapin Track" },
  { id: 529, name: "Lapis" },
  { id: 896, name: "Larx Entertainment" },
  { id: 1408, name: "Lastrum Music" },
  { id: 1496, name: "Lawson" },
  { id: 2031, name: "Lawson Entertainment" },
  { id: 1309, name: "Lawson HMV Entertainment" },
  { id: 1087, name: "Lay-duce" },
  { id: 1268, name: "L²Studio" },
  { id: 2336, name: "Lead" },
  { id: 1908, name: "Legs" },
  { id: 414, name: "Lemon Heart" },
  { id: 456, name: "Lerche" },
  { id: 1829, name: "Lesprit" },
  { id: 1428, name: "Level-5" },
  { id: 2142, name: "LEVELS" },
  { id: 2113, name: "Liber Entertainment" },
  { id: 1936, name: "Liberty Animation Studio" },
  { id: 1905, name: "Libre" },
  { id: 2125, name: "LICO" },
  { id: 1945, name: "Lide" },
  { id: 839, name: "LIDENFILMS" },
  { id: 2306, name: "LIDENFILMS Kyoto Studio" },
  { id: 1982, name: "LIDENFILMS Osaka Studio" },
  { id: 312, name: "Life Work" },
  { id: 1485, name: "Light Chaser Animation Studios" },
  { id: 1759, name: "Lilix" },
  { id: 1777, name: "LINE Corporation" },
  { id: 2211, name: "Ling San Wu Donghua" },
  { id: 1865, name: "LinkedBrain" },
  { id: 1798, name: "Links" },
  { id: 1823, name: "Live Viewing Japan" },
  { id: 1995, name: "Live2D Creative Studio" },
  { id: 1017, name: "Liverpool" },
  { id: 565, name: "LMD" },
  { id: 2354, name: "LOGIC&amp;MAGIC" },
  { id: 1123, name: "Lucent Pictures Entertainment" },
  { id: 657, name: "Lucky Paradise" },
  { id: 823, name: "Lune Pictures" },
  { id: 2025, name: "Lute" },
  { id: 2143, name: "LX Animation Studio" },
  { id: 40, name: "m.o.e." },
  { id: 463, name: "M.S.C" },
  { id: 2316, name: "Maboroshi Koubou" },
  { id: 430, name: "Mad Box" },
  { id: 11, name: "Madhouse" },
  { id: 1452, name: "Mag Garden" },
  { id: 963, name: "MAGES." },
  { id: 1860, name: "Magia Doraglier" },
  { id: 207, name: "Magic Bus" },
  { id: 306, name: "Magic Capsule" },
  { id: 1073, name: "Magic Lantern Film" },
  { id: 2213, name: "Magma Studio" },
  { id: 1996, name: "MAGNET" },
  { id: 1978, name: "Maho Film" },
  { id: 490, name: "Maiden Japan" },
  { id: 449, name: "Maikaze" },
  { id: 143, name: "Mainichi Broadcasting System" },
  { id: 1603, name: "Mainichi Shimbun" },
  { id: 767, name: "Majin" },
  { id: 2069, name: "Making Animation" },
  { id: 947, name: "Manga Entertainment" },
  { id: 2283, name: "Manga Productions" },
  { id: 32, name: "Manglobe" },
  { id: 569, name: "MAPPA" },
  { id: 1363, name: "Marine Entertainment" },
  { id: 2040, name: "Maro Studio" },
  { id: 2188, name: "Marone" },
  { id: 320, name: "Maru Production" },
  { id: 165, name: "Marubeni" },
  { id: 1800, name: "Marui Group" },
  { id: 483, name: "Marvel Entertainment" },
  { id: 82, name: "Marvelous" },
  { id: 751, name: "Marvelous AQL" },
  { id: 553, name: "Marvy Jack" },
  { id: 424, name: "Mary Jane" },
  { id: 1296, name: "Marza Animation Planet" },
  { id: 1849, name: "MASTER LIGHTS" },
  { id: 1937, name: "MAT" },
  { id: 1891, name: "Mattel Creations" },
  { id: 997, name: "Maxell E-Cube" },
  { id: 2162, name: "Maxilla" },
  { id: 1877, name: "MAZRI" },
  { id: 637, name: "Möbius Tone" },
  { id: 250, name: "Media Blasters" },
  { id: 1280, name: "Media Castle" },
  { id: 1520, name: "Media Do" },
  { id: 108, name: "Media Factory" },
  { id: 1378, name: "Media Rings" },
  { id: 1424, name: "Mediabank" },
  { id: 2279, name: "MediaLink Entertainment Limited" },
  { id: 135, name: "MediaNet" },
  { id: 2222, name: "MediaNet Pictures" },
  { id: 1337, name: "Medicos Entertainment" },
  { id: 1438, name: "Medicrie" },
  { id: 1403, name: "Meiji Seika" },
  { id: 2339, name: "Melissa" },
  { id: 71, name: "Mellow Head" },
  { id: 1821, name: "Melonbooks" },
  { id: 2330, name: "Meltdown" },
  { id: 647, name: "Memory-Tech" },
  { id: 1754, name: "Meruhensha" },
  { id: 2365, name: "MI" },
  { id: 1896, name: "Micro Magazine Publishing" },
  { id: 2308, name: "Midorimatsu" },
  { id: 2253, name: "MiHoYoAnime" },
  { id: 1305, name: "Milestone Music Publishing" },
  { id: 1810, name: "Mili Pictures" },
  { id: 1027, name: "Milkshake" },
  { id: 25, name: "Milky Animation Label" },
  { id: 398, name: "Milky Cartoon" },
  { id: 2280, name: "Mill Creek Entertainment" },
  { id: 1237, name: "Millepensee" },
  { id: 2103, name: "Mime Corporation" },
  { id: 2177, name: "Mimoid" },
  { id: 1725, name: "Minakata Laboratory" },
  { id: 442, name: "Minami Machi Bugyousho" },
  { id: 1477, name: "Ministry of the Navy" },
  { id: 1441, name: "Mippei Eigeki Kiryuukan" },
  { id: 1406, name: "Miracle Bus" },
  { id: 763, name: "Miracle Robo" },
  { id: 1249, name: "Mirai Film" },
  { id: 1644, name: "Mirai Records" },
  { id: 2186, name: "Mirai-Kojo" },
  { id: 1756, name: "Miraicha Records" },
  { id: 501, name: "Miramax Films" },
  { id: 394, name: "Misseri Studio" },
  { id: 1247, name: "Mistral Japan" },
  { id: 1564, name: "Mitsubishi" },
  { id: 2098, name: "Mixer" },
  { id: 1699, name: "Miyagi Television Broadcasting" },
  { id: 2224, name: "Miyazaki Broadcasting" },
  { id: 1179, name: "MK Pictures" },
  { id: 1077, name: "MMDGP" },
  { id: 2267, name: "MMT Technology" },
  { id: 1213, name: "Mobcast" },
  { id: 2064, name: "Mokai Technology" },
  { id: 1854, name: "monofilmo" },
  { id: 1409, name: "Monomusik" },
  { id: 1973, name: "Monster's Egg" },
  { id: 1193, name: "MooGoo" },
  { id: 54, name: "Mook Animation" },
  { id: 1442, name: "Mook DLE" },
  { id: 1730, name: "Moonbell" },
  { id: 495, name: "Moonstone Cherry" },
  { id: 2054, name: "MORIE Inc." },
  { id: 1525, name: "Moss Design Unit" },
  { id: 1827, name: "Motion Magic" },
  { id: 2334, name: "Mouse" },
  { id: 2322, name: "Mousou Senka" },
  { id: 166, name: "Movic" },
  { id: 319, name: "MS Pictures" },
  { id: 1786, name: "Muse Communication" },
  { id: 1919, name: "Muse International" },
  { id: 68, name: "Mushi Production" },
  { id: 1682, name: "Music Ray'n" },
  { id: 1744, name: "My Theater D.D." },
  { id: 2045, name: "Myrica Music" },
  { id: 1472, name: "Myung Films" },
  { id: 533, name: "N&amp;G Production" },
  { id: 1612, name: "NADA Holdings" },
  { id: 1366, name: "Nagoya Broadcasting Network" },
  { id: 1260, name: "Nakamura Production" },
  { id: 1915, name: "Namisokan" },
  { id: 1536, name: "Namu Animation" },
  { id: 266, name: "Natural High" },
  { id: 2044, name: "Naver Webtoons" },
  { id: 951, name: "NAZ" },
  { id: 1113, name: "NBCUniversal Entertainment Japan" },
  { id: 1446, name: "NEC Avenue" },
  { id: 1387, name: "Neft Film" },
  { id: 1555, name: "Nelke Planning" },
  { id: 215, name: "Nelvana" },
  { id: 2146, name: "NetEase" },
  { id: 1977, name: "Netflix" },
  { id: 1448, name: "Network" },
  { id: 2277, name: "Network Kouenji Studio" },
  { id: 2269, name: "New Generation" },
  { id: 1779, name: "NewGin" },
  { id: 677, name: "Nexon" },
  { id: 1491, name: "Next" },
  { id: 819, name: "Next Media Animation" },
  { id: 852, name: "Nexus" },
  { id: 111, name: "NHK" },
  { id: 1797, name: "NHK Enterprises" },
  { id: 359, name: "NHK-BS2" },
  { id: 1712, name: "NHN PlayArt" },
  { id: 1825, name: "NIANTIC" },
  { id: 1804, name: "Nice Boat Animation" },
  { id: 428, name: "Nichiei Agency" },
  { id: 1589, name: "NichiNare" },
  { id: 1585, name: "Nichion" },
  { id: 801, name: "Nihikime no Dozeu" },
  { id: 139, name: "Nihon Ad Systems" },
  { id: 1532, name: "Nihon Eizo" },
  { id: 468, name: "Nihon Falcom" },
  { id: 989, name: "Nihon Hoso Eigasha" },
  { id: 2219, name: "Nihon Keizai Koukokusha" },
  { id: 513, name: "Nikkatsu" },
  { id: 1167, name: "Nikkatsu Mukojima" },
  { id: 503, name: "Nintendo" },
  { id: 505, name: "Nintendo of America" },
  { id: 22, name: "Nippon Animation" },
  { id: 323, name: "Nippon Columbia" },
  { id: 1577, name: "Nippon Cultural Broadcasting" },
  { id: 1623, name: "Nippon Ichi Software" },
  { id: 2010, name: "Nippon Ramayana Film Co." },
  { id: 316, name: "Nippon Shuppan Hanbai (Nippan) K.K." },
  { id: 1418, name: "Nippon Television Music" },
  { id: 1003, name: "Nippon Television Network" },
  { id: 372, name: "NIS America, Inc." },
  { id: 1670, name: "Nishiki Studio" },
  { id: 1548, name: "Nishinippon Broadcasting" },
  { id: 459, name: "Nitroplus" },
  { id: 2160, name: "Nobel" },
  { id: 70, name: "Nomad" },
  { id: 2303, name: "Noovo" },
  { id: 1534, name: "North Stars Pictures" },
  { id: 2302, name: "Nostalook" },
  { id: 703, name: "Notes" },
  { id: 892, name: "NOTTV" },
  { id: 217, name: "Nozomi Entertainment" },
  { id: 689, name: "NTT Docomo" },
  { id: 1614, name: "NTT Plala" },
  { id: 2014, name: "Nur" },
  { id: 1567, name: "Nut" },
  { id: 270, name: "NuTech Digital" },
  { id: 595, name: "NYAV Post" },
  { id: 67, name: "OB Planning" },
  { id: 571, name: "Obtain Future" },
  { id: 1921, name: "OCC" },
  { id: 1809, name: "October Media" },
  { id: 1005, name: "Oddjob" },
  { id: 1473, name: "Odolttogi" },
  { id: 429, name: "Office AO" },
  { id: 1281, name: "Office DCI" },
  { id: 2286, name: "Office ENDLESS" },
  { id: 2315, name: "Office No. 8" },
  { id: 1300, name: "Office Nobu" },
  { id: 481, name: "Office Take Off" },
  { id: 1374, name: "Office Takeout" },
  { id: 234, name: "Oh! Production" },
  { id: 2361, name: "Okumaza" },
  { id: 2037, name: "Okuruto Noboru" },
  { id: 461, name: "OLE-M" },
  { id: 1171, name: "Olive Studio" },
  { id: 28, name: "OLM" },
  { id: 1231, name: "OLM Digital" },
  { id: 2326, name: "OLM Team Yoshioka" },
  { id: 313, name: "Omnibus Japan" },
  { id: 1624, name: "On The Run" },
  { id: 1600, name: "On-Lead" },
  { id: 1783, name: "ONEMUSIC" },
  { id: 1863, name: "Ongaq" },
  { id: 2345, name: "Onion Studio" },
  { id: 1717, name: "Onionskin" },
  { id: 1013, name: "Opera House" },
  { id: 2318, name: "ORADA COMPANY" },
  { id: 1109, name: "Orange" },
  { id: 1654, name: "Orchid Seed" },
  { id: 334, name: "Ordet" },
  { id: 2193, name: "ORENDA" },
  { id: 2172, name: "Original Dream" },
  { id: 2065, name: "Original Force" },
  { id: 1924, name: "Orix" },
  { id: 1273, name: "Osaka University of Arts" },
  { id: 831, name: "Otogi Production" },
  { id: 1443, name: "Overlap" },
  { id: 361, name: "Oxybot" },
  { id: 2204, name: "OZ" },
  { id: 395, name: "Oz Inc." },
  { id: 2353, name: "P core" },
  { id: 985, name: "P Productions" },
  { id: 1715, name: "P-Vine Records" },
  { id: 132, name: "P.A. Works" },
  { id: 1872, name: "P.I.C.S." },
  { id: 2073, name: "Painting Dream" },
  { id: 455, name: "Palm Studio" },
  { id: 1565, name: "Panasonic Digital Contents" },
  { id: 2047, name: "Pancake" },
  { id: 373, name: "Panda Factory" },
  { id: 226, name: "Panmedia" },
  { id: 1303, name: "PansonWorks" },
  { id: 2171, name: "Paper Animation" },
  { id: 2310, name: "Paper Plane Animation Studio" },
  { id: 1688, name: "Parco" },
  { id: 862, name: "Pashmina" },
  { id: 911, name: "Passione" },
  { id: 413, name: "Pastel" },
  { id: 1568, name: "Pazzy Entertainment" },
  { id: 1771, name: "Pb Animation Co. Ltd." },
  { id: 2013, name: "Peak Hunt" },
  { id: 1478, name: "Pencil" },
  { id: 1354, name: "Penta Show Studios" },
  { id: 2122, name: "PERIMETRON" },
  { id: 773, name: "Peter Pan Creation" },
  { id: 1751, name: "pH Studio" },
  { id: 329, name: "Phoenix Entertainment" },
  { id: 2111, name: "Pia" },
  { id: 1758, name: "Picante Circus" },
  { id: 293, name: "Picograph" },
  { id: 1764, name: "Picona" },
  { id: 78, name: "Picture Magic" },
  { id: 1229, name: "Pie in the sky" },
  { id: 1467, name: "Pied Piper" },
  { id: 1129, name: "Pierrot Plus" },
  { id: 1382, name: "Piko Studio" },
  { id: 1295, name: "Pine Jam" },
  { id: 45, name: "Pink Pineapple" },
  { id: 204, name: "Pioneer LDC" },
  { id: 1762, name: "Piso Studio" },
  { id: 195, name: "Pixy" },
  { id: 175, name: "Planet" },
  { id: 2266, name: "Planet Nemo Animation" },
  { id: 1471, name: "Platinum Vision" },
  { id: 107, name: "Plum" },
  { id: 374, name: "Plus Heads" },
  { id: 1630, name: "Plus One" },
  { id: 807, name: "Po10tial" },
  { id: 2268, name: "Point Pictures" },
  { id: 1290, name: "Pollyanna Graphics" },
  { id: 2207, name: "Poly Animation" },
  { id: 1938, name: "Polygon Magic" },
  { id: 1023, name: "Polygon Pictures" },
  { id: 156, name: "Polygram Japan" },
  { id: 931, name: "Poncotan" },
  { id: 2195, name: "PONOS Corporation" },
  { id: 144, name: "Pony Canyon" },
  { id: 1557, name: "Pony Canyon Enterprise" },
  { id: 1201, name: "Ponycan USA" },
  { id: 1049, name: "PoPoCo" },
  { id: 1746, name: "Pops Inc." },
  { id: 365, name: "PoRO" },
  { id: 448, name: "Postgal Workshop" },
  { id: 2349, name: "Potato House" },
  { id: 2342, name: "PP Project" },
  { id: 137, name: "PPM" },
  { id: 709, name: "PPP" },
  { id: 753, name: "PRA" },
  { id: 1931, name: "Presidio" },
  { id: 304, name: "Primastea" },
  { id: 347, name: "PrimeTime" },
  { id: 431, name: "Procidis" },
  { id: 2157, name: "Production +h." },
  { id: 1651, name: "Production Ace" },
  { id: 2321, name: "Production D.M.H" },
  { id: 1669, name: "production doA" },
  { id: 1317, name: "Production GoodBook" },
  { id: 10, name: "Production I.G" },
  { id: 1053, name: "Production IMS" },
  { id: 196, name: "Production Reed" },
  { id: 1508, name: "project lights" },
  { id: 439, name: "Project No.9" },
  { id: 1061, name: "Project Team Eikyuu Kikan" },
  { id: 2276, name: "Project Team Sarah" },
  { id: 1404, name: "PSG" },
  { id: 1065, name: "Public &amp; Basic" },
  { id: 559, name: "Purple Cow Studio Japan" },
  { id: 343, name: "Puzzle Animation Studio Limited" },
  { id: 1287, name: "Q-Tec" },
  { id: 2140, name: "Qianqi Animation" },
  { id: 2274, name: "Qiying Animation" },
  { id: 1655, name: "QREAZY" },
  { id: 2314, name: "Quad" },
  { id: 1304, name: "Qualia Animation" },
  { id: 1574, name: "Quaras" },
  { id: 1595, name: "Quatre Stella" },
  { id: 1975, name: "Qubic Pictures" },
  { id: 2243, name: "Quebico" },
  { id: 977, name: "Queen Bee" },
  { id: 1739, name: "Quick Corporation" },
  { id: 2288, name: "Qzil.la" },
  { id: 1417, name: "RAB Aomori Broadcasting" },
  { id: 1107, name: "Rabbit Gate" },
  { id: 1362, name: "Rabbit Machine" },
  { id: 1631, name: "Radio Osaka" },
  { id: 81, name: "Radix" },
  { id: 729, name: "Raku High Student Council" },
  { id: 211, name: "Rakuonsha" },
  { id: 1817, name: "Rakuten" },
  { id: 1410, name: "Rambling Records" },
  { id: 607, name: "RAMS" },
  { id: 339, name: "Rankin/Bass" },
  { id: 1581, name: "RAY" },
  { id: 190, name: "RCC Chugoku Broadcasting" },
  { id: 1454, name: "REALTHING" },
  { id: 2126, name: "Red Dog Culture House" },
  { id: 2273, name: "Reddog Culture House" },
  { id: 2209, name: "Reiki Eyes Animation" },
  { id: 49, name: "Remic" },
  { id: 1692, name: "Revoroot" },
  { id: 1850, name: "Rex Entertainment" },
  { id: 1181, name: "RG Animation Studios" },
  { id: 2018, name: "Rialto Entertainment" },
  { id: 661, name: "Right Gauge" },
  { id: 1394, name: "RightTracks" },
  { id: 253, name: "Rikuentai" },
  { id: 1187, name: "Ripple Film" },
  { id: 1489, name: "Ripromo" },
  { id: 1519, name: "Rironsha" },
  { id: 1067, name: "Rising Force" },
  { id: 1888, name: "RME" },
  { id: 249, name: "Robot Communications" },
  { id: 2281, name: "Rocen" },
  { id: 1618, name: "Rockwell Eyes" },
  { id: 1302, name: "RoiVisual" },
  { id: 591, name: "Romanov Films" },
  { id: 1293, name: "Romantica club !!" },
  { id: 160, name: "Rondo Robe" },
  { id: 2187, name: "Royal Limousine" },
  { id: 446, name: "RTHK" },
  { id: 264, name: "Ruby-Spears Productions" },
  { id: 2042, name: "Ruo Hong Culture" },
  { id: 1741, name: "RX-RECORDS" },
  { id: 913, name: "Ryukyu Asahi Broadcasting" },
  { id: 1875, name: "S-TAR7" },
  { id: 1323, name: "Saban Brands" },
  { id: 841, name: "Saban Entertainment" },
  { id: 1853, name: "Saetta" },
  { id: 1934, name: "Saigo no Shudan" },
  { id: 1242, name: "Sakura Color Film" },
  { id: 765, name: "Sakura Create" },
  { id: 1298, name: "Sakura Motion Picture" },
  { id: 611, name: "Sakura Production" },
  { id: 341, name: "SamBakZa" },
  { id: 1345, name: "Sammy" },
  { id: 1944, name: "Samsara Animation Studio" },
  { id: 1914, name: "Samsung" },
  { id: 261, name: "San-X" },
  { id: 1270, name: "Sanctuary" },
  { id: 1311, name: "Sankyo Planning" },
  { id: 150, name: "Sanrio" },
  { id: 1151, name: "Sanrio Digital" },
  { id: 1515, name: "Sanyo" },
  { id: 1552, name: "Sanyo Bussan" },
  { id: 537, name: "SANZIGEN" },
  { id: 1698, name: "Sapporo Television Broadcasting" },
  { id: 41, name: "Satelight" },
  { id: 98, name: "Sav! The World Productions" },
  { id: 2117, name: "SB Creative" },
  { id: 523, name: "SBS TV Production" },
  { id: 2324, name: "Scarlet" },
  { id: 422, name: "Schoolzone" },
  { id: 1591, name: "Science SARU" },
  { id: 1308, name: "SEDIC International" },
  { id: 167, name: "Sega" },
  { id: 1910, name: "Sega Interactive" },
  { id: 701, name: "Seikaisha" },
  { id: 1137, name: "SEK Studios" },
  { id: 1836, name: "SELFISH" },
  { id: 376, name: "Sentai Filmworks" },
  { id: 335, name: "Seta Corporation" },
  { id: 541, name: "Seven" },
  { id: 35, name: "Seven Arcs" },
  { id: 1569, name: "Seven Arcs Pictures" },
  { id: 1830, name: "Seven Stone Entertainment" },
  { id: 44, name: "Shaft" },
  { id: 471, name: "Shanghai Animation Film Studio" },
  {
    id: 1667,
    name: "Shanghai Foch Film and TV Culture Investment",
  },
  { id: 1844, name: "Shanghai Hippo Animation" },
  { id: 1818, name: "Shanghai Jump Network Technology" },
  { id: 1611, name: "Shanghai Tiantan Culture &amp; Media" },
  { id: 2258, name: "Sharefun Studio" },
  { id: 168, name: "Shelty" },
  { id: 2058, name: "Shenying Animation" },
  { id: 1324, name: "Shimogumi" },
  { id: 247, name: "Shin-Ei Animation" },
  { id: 1147, name: "Shinano Kikaku" },
  { id: 1550, name: "Shinchosha" },
  { id: 2335, name: "Shindeban Film" },
  { id: 2329, name: "Shinjukuza" },
  { id: 192, name: "Shinkuukan" },
  { id: 1672, name: "Shinshokan" },
  { id: 485, name: "Shinwon Productions" },
  { id: 133, name: "Shinyusha" },
  { id: 2332, name: "Shion" },
  { id: 235, name: "Shirogumi" },
  { id: 2036, name: "Shizuoka Asahi Television" },
  { id: 1359, name: "Shizuoka Broadcasting System" },
  { id: 1700, name: "Shizuoka Daiichi Television" },
  { id: 109, name: "Shochiku" },
  { id: 1476, name: "Shochiku Animation Institute" },
  { id: 1894, name: "Shochiku Media Division" },
  { id: 1626, name: "Shochiku Music Publishing" },
  { id: 1765, name: "Shodensha" },
  { id: 1430, name: "Shogakukan" },
  {
    id: 474,
    name: "Shogakukan Music &amp; Digital Entertainment",
  },
  { id: 62, name: "Shogakukan-Shueisha Productions" },
  { id: 1553, name: "Shounen Gahousha" },
  { id: 1737, name: "Shout! Factory" },
  { id: 2148, name: "Show Corporation" },
  { id: 777, name: "Showgate" },
  { id: 2215, name: "Showten" },
  { id: 1365, name: "Shueisha" },
  { id: 1708, name: "Shufunotomo" },
  { id: 1119, name: "Shuka" },
  { id: 2154, name: "Shun Produce" },
  { id: 2331, name: "Shura" },
  { id: 260, name: "Shuuhei Morita" },
  { id: 1420, name: "SIDO LIMITED" },
  { id: 1278, name: "Signal.MD" },
  { id: 129, name: "Silky’s" },
  { id: 1873, name: "Silver" },
  { id: 300, name: "SILVER LINK." },
  { id: 2284, name: "SJYNEXCUS" },
  { id: 279, name: "Skouras" },
  { id: 2189, name: "Sky Perfect Communications" },
  { id: 147, name: "SKY Perfect Well Think" },
  { id: 1859, name: "SKY PerfecTV!" },
  { id: 735, name: "Slow Curve" },
  { id: 1918, name: "SME Records" },
  { id: 149, name: "SME Visual Works" },
  { id: 2293, name: "Smile Company" },
  { id: 1647, name: "Smiral Animation" },
  { id: 1372, name: "Soeishinsha" },
  { id: 254, name: "Soft Garage" },
  { id: 953, name: "Soft on Demand" },
  { id: 621, name: "SoftBank Creative" },
  { id: 813, name: "SoftCel Pictures" },
  { id: 153, name: "SoftX" },
  { id: 161, name: "Sogo Vision" },
  { id: 209, name: "Sol Blade" },
  { id: 1189, name: "Sola Digital Arts" },
  { id: 2019, name: "Sola Entertainment" },
  { id: 854, name: "Solid Vox" },
  { id: 1858, name: "Sonilude" },
  { id: 2328, name: "Sonsan Kikaku" },
  { id: 2000, name: "Sony Creative Products" },
  { id: 1950, name: "Sony Interactive Entertainment" },
  { id: 737, name: "Sony Music Communications" },
  { id: 757, name: "Sony Music Entertainment" },
  { id: 2106, name: "Sony Music Solutions" },
  { id: 1516, name: "Sony PCL" },
  { id: 15, name: "Sony Pictures Entertainment" },
  { id: 1928, name: "Sony Pictures Worldwide Acquisitions" },
  { id: 64, name: "Sotsu" },
  { id: 1597, name: "Sotsu Music Publishing" },
  { id: 1294, name: "Sound Team Don Juan" },
  { id: 1909, name: "Souten no Ken" },
  { id: 128, name: "Souten Studio" },
  { id: 364, name: "Sovat Theater" },
  { id: 2059, name: "Soyep" },
  { id: 679, name: "Soyuzmultfilm" },
  { id: 1045, name: "Space Neko Company" },
  { id: 1343, name: "Space Shower Music" },
  { id: 2333, name: "Space-X" },
  { id: 1732, name: "Spacey Music Entertainment" },
  { id: 1768, name: "Sparkly Key Animation Studio" },
  { id: 581, name: "Sparky Animation" },
  { id: 979, name: "SPEED" },
  { id: 1932, name: "Speed Inc." },
  { id: 2063, name: "Spell Bound" },
  { id: 1391, name: "SPO Entertainment" },
  { id: 2250, name: "Spooky graphic" },
  { id: 2023, name: "Spoon" },
  { id: 1370, name: "Sprite Animation Studios" },
  { id: 58, name: "Square Enix" },
  { id: 1847, name: "Square Enix Visual Works" },
  { id: 92, name: "Starchild Records" },
  { id: 1601, name: "Stardust Promotion" },
  { id: 2233, name: "Starry Cube" },
  { id: 2028, name: "Stella Promotion" },
  { id: 1197, name: "Steve N' Steven" },
  { id: 1436, name: "Stingray" },
  { id: 1956, name: "STORY" },
  { id: 2295, name: "Story Effect" },
  { id: 1960, name: "StoryRiders Co. Ltd." },
  { id: 1683, name: "Straight Edge" },
  { id: 884, name: "Strawberry Meets Pictures" },
  { id: 2062, name: "Stray Cats" },
  { id: 1203, name: "Studio 1st" },
  { id: 1127, name: "Studio 3Hz" },
  { id: 13, name: "Studio 4°C" },
  { id: 2169, name: "Studio 88" },
  { id: 407, name: "Studio 9 Maiami" },
  { id: 1209, name: "Studio A-CAT" },
  { id: 999, name: "Studio Animal" },
  { id: 1966, name: "Studio Arch Inc." },
  { id: 1641, name: "Studio AWAKE" },
  { id: 1993, name: "Studio Bind" },
  { id: 1252, name: "Studio Binzo" },
  { id: 478, name: "Studio Blanc" },
  { id: 338, name: "Studio Bogey" },
  { id: 2327, name: "Studio Boogie Nights" },
  { id: 1750, name: "Studio CA" },
  { id: 1149, name: "Studio Cab" },
  { id: 1666, name: "Studio Carbuncle" },
  { id: 1599, name: "Studio CHANT" },
  { id: 555, name: "Studio Chizu" },
  { id: 2051, name: "Studio Coa" },
  { id: 1095, name: "Studio Cockpit" },
  { id: 1033, name: "Studio Colorido" },
  { id: 126, name: "Studio Comet" },
  { id: 959, name: "Studio Compile" },
  { id: 1479, name: "Studio Core" },
  { id: 1927, name: "Studio Crocodile" },
  { id: 1259, name: "Studio Curtain" },
  { id: 1173, name: "Studio Dadashow" },
  { id: 2240, name: "Studio Daisy" },
  { id: 37, name: "Studio Deen" },
  { id: 545, name: "Studio Deva Loka" },
  { id: 2007, name: "Studio Drive" },
  { id: 2196, name: "Studio DURIAN" },
  { id: 409, name: "Studio Egg" },
  { id: 1521, name: "Studio elle" },
  { id: 423, name: "Studio Eromatick" },
  { id: 24, name: "Studio Fantasia" },
  { id: 1693, name: "Studio Flad" },
  { id: 93, name: "Studio Flag" },
  { id: 427, name: "Studio G-1Neo" },
  { id: 2351, name: "Studio Gadget" },
  { id: 1227, name: "Studio GDW" },
  { id: 21, name: "Studio Ghibli" },
  { id: 2244, name: "Studio Gohan" },
  { id: 418, name: "Studio Gokumi" },
  { id: 1253, name: "Studio GOONEYS" },
  { id: 497, name: "Studio Gram" },
  { id: 2282, name: "Studio Guts" },
  { id: 1814, name: "Studio Hakk" },
  { id: 2313, name: "studio hb" },
  { id: 101, name: "Studio Hibari" },
  { id: 1968, name: "Studio Hokiboshi" },
  { id: 117, name: "Studio Izena" },
  { id: 829, name: "Studio Jack" },
  { id: 1375, name: "Studio Jam" },
  { id: 2300, name: "Studio Jemi" },
  { id: 280, name: "Studio Junio" },
  { id: 937, name: "Studio Kaab" },
  { id: 2205, name: "Studio Kafka" },
  { id: 1997, name: "Studio Kai" },
  { id: 272, name: "Studio Kajino" },
  { id: 909, name: "Studio Kelmadick" },
  { id: 1705, name: "Studio Khronos" },
  { id: 256, name: "Studio Kikan" },
  { id: 2252, name: "Studio Kingyoiro" },
  { id: 1115, name: "Studio Korumi" },
  { id: 440, name: "Studio Kuma" },
  { id: 177, name: "Studio Kyuuma" },
  { id: 1774, name: "Studio LAN" },
  { id: 973, name: "Studio Liberty" },
  { id: 1813, name: "Studio Lings" },
  { id: 1383, name: "Studio Live" },
  { id: 1071, name: "Studio Lotus" },
  { id: 1529, name: "Studio M2" },
  { id: 1505, name: "Studio March" },
  { id: 114, name: "Studio Matrix" },
  { id: 719, name: "Studio Mausu" },
  { id: 1426, name: "Studio Meditation With a Pencil" },
  { id: 1776, name: "Studio Mir" },
  { id: 1248, name: "Studio Mirai" },
  { id: 1155, name: "Studio Moriken" },
  { id: 2246, name: "studio MOTHER" },
  { id: 487, name: "Studio MWP" },
  { id: 1763, name: "Studio Nanahoshi" },
  { id: 1059, name: "Studio Nem" },
  { id: 781, name: "Studio NOIX" },
  { id: 2296, name: "Studio Nuck" },
  { id: 199, name: "Studio Nue" },
  { id: 1724, name: "Studio OX" },
  { id: 2201, name: "Studio Palette" },
  { id: 299, name: "Studio Pastoral" },
  { id: 1, name: "Studio Pierrot" },
  { id: 1523, name: "Studio Ponoc" },
  { id: 1839, name: "Studio Ppuri" },
  { id: 2341, name: "Studio Prokion" },
  { id: 443, name: "Studio PuYUKAI" },
  { id: 2271, name: "Studio RE:Map" },
  { id: 84, name: "Studio Rikka" },
  { id: 543, name: "Studio Saki Makura" },
  { id: 1852, name: "Studio Shamrock" },
  { id: 2130, name: "Studio Shelter" },
  { id: 629, name: "Studio Sign" },
  { id: 438, name: "Studio Signal" },
  { id: 1998, name: "Studio Signpost" },
  { id: 2337, name: "Studio Soul" },
  { id: 494, name: "Studio Take Off" },
  { id: 2338, name: "Studio Ten" },
  { id: 1352, name: "Studio Ten Carat" },
  { id: 216, name: "Studio Tron" },
  { id: 210, name: "Studio Tulip" },
  { id: 1691, name: "Studio UGOKI" },
  { id: 404, name: "Studio Unicorn" },
  { id: 1244, name: "Studio VOLN" },
  { id: 1871, name: "Studio W.Baba" },
  { id: 1533, name: "Studio WHO" },
  { id: 412, name: "Studio Wombat" },
  { id: 1509, name: "Studio World" },
  { id: 1504, name: "Studio Z5" },
  { id: 1089, name: "Studio Zain" },
  { id: 903, name: "Studio Zealot" },
  { id: 435, name: "Studio Zero" },
  { id: 1266, name: "Studio! Cucuri" },
  { id: 2145, name: "studioGONG" },
  { id: 549, name: "StudioRF Inc." },
  { id: 1608, name: "SUBARU" },
  { id: 1892, name: "Sublimation" },
  { id: 1593, name: "Success Corp." },
  { id: 1348, name: "Sugar Boy" },
  { id: 1760, name: "Suiseisha" },
  { id: 1507, name: "Sumitomo" },
  { id: 2260, name: "Sumzap" },
  { id: 1604, name: "Sun TV" },
  { id: 1979, name: "Suna Kouhou" },
  { id: 761, name: "Sunny Side Up" },
  { id: 14, name: "Sunrise" },
  { id: 2004, name: "Sunrise Beyond" },
  { id: 1543, name: "Sunrise Music Publishing" },
  { id: 307, name: "Sunwoo Entertainment" },
  { id: 2108, name: "SUPA LOVE" },
  { id: 2164, name: "Super Brain" },
  { id: 2080, name: "Super Normal Studio" },
  { id: 1364, name: "Super Techno Arts" },
  { id: 2161, name: "Suspenders" },
  { id: 274, name: "Suzuki Mirano" },
  { id: 2003, name: "syn Sophia" },
  { id: 1474, name: "Synch-Point" },
  { id: 434, name: "Synergy Japan" },
  { id: 118, name: "SynergySP" },
  { id: 1935, name: "T-JOY" },
  { id: 405, name: "T-Rex" },
  { id: 1015, name: "T.O Entertainment" },
  { id: 1371, name: "T.P.O" },
  { id: 1622, name: "Tablier Communications" },
  { id: 2208, name: "Taikong Works" },
  { id: 917, name: "Takahashi Studio" },
  { id: 327, name: "Takara" },
  { id: 1421, name: "Takara Tomy A.R.T.S" },
  { id: 332, name: "Takeshobo" },
  { id: 345, name: "TAKI Corporation" },
  { id: 2214, name: "Takun Manga Box" },
  { id: 939, name: "Tama Production" },
  { id: 2307, name: "Tamabi" },
  { id: 2235, name: "tamakoshi" },
  { id: 388, name: "Tamura Shigeru Studio" },
  { id: 2141, name: "TANOsim" },
  { id: 2075, name: "Taomee" },
  { id: 416, name: "TAP" },
  { id: 2182, name: "Tapioca" },
  { id: 103, name: "Tatsunoko Production" },
  { id: 1761, name: "Tavac" },
  { id: 145, name: "TBS" },
  { id: 1283, name: "TC Entertainment" },
  { id: 489, name: "TCJ" },
  { id: 1335, name: "TEAM Entertainment Inc." },
  { id: 2027, name: "Team TillDawn" },
  { id: 1562, name: "Team YokkyuFuman" },
  { id: 949, name: "teamKG" },
  { id: 1890, name: "Tear Studio" },
  { id: 2163, name: "Teatro Nishi Tokyo Studio" },
  { id: 2178, name: "Tecarat" },
  { id: 1499, name: "Techno Sound" },
  { id: 1223, name: "Teichiku Entertainment" },
  { id: 385, name: "Tele-Cartoon Japan" },
  { id: 94, name: "Telecom Animation Film" },
  { id: 358, name: "Telescreen" },
  { id: 2136, name: "Ten Tails Animation" },
  { id: 1349, name: "Tencent Animation &amp; Comics" },
  { id: 1880, name: "Tencent Games" },
  { id: 1617, name: "Tencent Japan" },
  { id: 1727, name: "Tencent Penguin Pictures" },
  { id: 1514, name: "Tengu Kobo" },
  { id: 1752, name: "Terada Mokei" },
  { id: 200, name: "Tezuka Productions" },
  { id: 229, name: "The Answer Studio" },
  { id: 476, name: "The Berich" },
  { id: 2184, name: "The Monk Studios" },
  { id: 1250, name: "The National Film Center Japan" },
  { id: 499, name: "The Pokemon Company International" },
  { id: 350, name: "The Village of Marchen" },
  { id: 273, name: "Think Corporation" },
  { id: 1684, name: "THINKR" },
  { id: 208, name: "Three Fat Samurai" },
  { id: 1726, name: "Three-d" },
  { id: 1805, name: "Thundray" },
  { id: 248, name: "Tin House" },
  { id: 2200, name: "TIS" },
  { id: 73, name: "TMS Entertainment" },
  { id: 2174, name: "TMS Music" },
  { id: 707, name: "TMS-Kyokuchi" },
  { id: 120, name: "TNK" },
  { id: 1988, name: "TO Books" },
  { id: 1757, name: "Tochigi TV" },
  { id: 1558, name: "TOCSIS" },
  { id: 2292, name: "Toei Agency" },
  { id: 18, name: "Toei Animation" },
  { id: 141, name: "Toei Video" },
  { id: 1734, name: "Tohan Corporation" },
  { id: 245, name: "Toho" },
  { id: 1143, name: "TOHO animation" },
  { id: 2057, name: "Toho Interactive Animation" },
  { id: 2229, name: "Toho Music" },
  { id: 1898, name: "Toho Visual Entertainment" },
  { id: 1870, name: "Toho-Towa" },
  { id: 577, name: "Tohokushinsha Film Corporation" },
  { id: 1455, name: "Tokai Television" },
  { id: 905, name: "Tokuma Japan" },
  { id: 1493, name: "Tokuma Japan Communications" },
  { id: 382, name: "Tokuma Shoten" },
  { id: 899, name: "Tokyo Animation Film" },
  { id: 1987, name: "Tokyo Animator Gakuin" },
  { id: 1625, name: "Tokyo FM Broadcasting" },
  { id: 122, name: "Tokyo Kids" },
  { id: 403, name: "Tokyo Media Connections" },
  { id: 1846, name: "Tokyo Movie" },
  { id: 65, name: "Tokyo Movie Shinsha" },
  { id: 1211, name: "Tokyo MX" },
  { id: 1319, name: "Tokyo Theatres" },
  { id: 484, name: "Tokyopop" },
  { id: 1312, name: "Tokyu Recreation" },
  { id: 587, name: "Tomason" },
  { id: 1265, name: "Tomovies" },
  { id: 366, name: "Tomoyasu Murata Company" },
  { id: 1458, name: "TOMY Company" },
  { id: 2084, name: "Tong Ming Xuan" },
  { id: 1356, name: "Tonko House" },
  { id: 1660, name: "Top Marshal" },
  { id: 1637, name: "Top-Insight International" },
  { id: 363, name: "Topcraft" },
  { id: 1620, name: "Toppan Printing" },
  { id: 882, name: "Toranoana" },
  { id: 1541, name: "Tose" },
  { id: 1685, name: "Toshiba Digital Frontiers" },
  { id: 224, name: "Toshiba EMI" },
  { id: 741, name: "Toshiba Entertainment" },
  { id: 671, name: "Toshima Entertainment" },
  { id: 1676, name: "Tosho Printing" },
  { id: 2030, name: "Tower Records" },
  { id: 1390, name: "Toy's Factory" },
  { id: 1985, name: "Toyo Recording" },
  { id: 80, name: "Trans Arts" },
  { id: 1316, name: "Trans Cosmos" },
  { id: 2239, name: "Transcendence Picture" },
  { id: 2050, name: "Trash Studio" },
  { id: 1165, name: "Tri-Slash" },
  { id: 110, name: "Triangle Staff" },
  { id: 384, name: "Trick Block" },
  { id: 1843, name: "TriF Studio" },
  { id: 803, name: "Trigger" },
  { id: 178, name: "Trilogy Future Studio" },
  { id: 63, name: "Trinet Entertainment" },
  { id: 643, name: "Trinity Sound" },
  { id: 2304, name: "TrioPen Studio" },
  { id: 860, name: "Triple X" },
  { id: 1103, name: "TROYCA" },
  { id: 1948, name: "TRUSS" },
  { id: 2352, name: "Tryforce" },
  { id: 901, name: "Tsubasa Entertainment" },
  { id: 453, name: "Tsuburaya Productions" },
  { id: 390, name: "Tsuchida Productions" },
  { id: 1638, name: "Tsukimidou" },
  { id: 1686, name: "Tsukuru no Mori" },
  { id: 2212, name: "Tsumugi Akita Animation Lab" },
  { id: 1884, name: "TSUTAYA" },
  { id: 2251, name: "TthunDer Animation" },
  { id: 1292, name: "TUBA" },
  { id: 1355, name: "TV Aichi" },
  { id: 55, name: "TV Asahi" },
  { id: 2234, name: "TV Asahi Music" },
  { id: 100, name: "TV Osaka" },
  { id: 1627, name: "TV Saitama" },
  { id: 1511, name: "TV Setouchi" },
  { id: 16, name: "TV Tokyo" },
  { id: 717, name: "TV Tokyo Music" },
  { id: 1650, name: "Twilight Studio" },
  { id: 1747, name: "Twin Engine" },
  { id: 1868, name: "Twin Planet" },
  { id: 2022, name: "TYMOTE" },
  { id: 1451, name: "TYO" },
  { id: 333, name: "TYO Animations" },
  { id: 1340, name: "Typhoon Graphics" },
  { id: 1583, name: "U-NEXT" },
  { id: 561, name: "U/M/A/A Inc." },
  { id: 43, name: "ufotable" },
  { id: 1742, name: "UK.PROJECT INC." },
  { id: 539, name: "Ultra Super Pictures" },
  { id: 368, name: "UM Productions" },
  { id: 371, name: "Union Cho" },
  { id: 1785, name: "Universal Entertainment" },
  { id: 1397, name: "Universal Music Japan" },
  { id: 1450, name: "Universal Pictures Japan" },
  { id: 1031, name: "Universal Radio Studio" },
  { id: 507, name: "Universal Studios" },
  { id: 1842, name: "Urban Product" },
  { id: 1447, name: "Urban Vision" },
  { id: 472, name: "Usagi Ou" },
  { id: 1615, name: "USEN" },
  { id: 1882, name: "UWAN Pictures" },
  { id: 1969, name: "V-sign" },
  { id: 265, name: "Valkyria" },
  { id: 1981, name: "Vanguard Sound" },
  { id: 2150, name: "Vanikey" },
  { id: 29, name: "VAP" },
  { id: 945, name: "Vasoon Animation" },
  { id: 136, name: "Vega Entertainment" },
  { id: 457, name: "Venet" },
  { id: 212, name: "Venus Vangard" },
  { id: 123, name: "Victor Entertainment" },
  { id: 2245, name: "Victor Studio" },
  { id: 2109, name: "Video Market" },
  { id: 433, name: "View Works" },
  { id: 733, name: "Viki" },
  { id: 1718, name: "Virgin Babylon Records" },
  { id: 246, name: "Visual 80" },
  { id: 203, name: "Visual Arts" },
  { id: 2129, name: "Visual Flight" },
  { id: 1518, name: "Visual Vision" },
  { id: 119, name: "VIZ Media" },
  { id: 655, name: "Volks" },
  { id: 1929, name: "voque ting" },
  { id: 1571, name: "Voyager Entertainment" },
  { id: 1964, name: "VV-ALKLINE" },
  { id: 1953, name: "W+K Tokyo" },
  { id: 1396, name: "W-Toon Studio" },
  { id: 450, name: "Wako Productions" },
  { id: 1400, name: "Walkers Company" },
  { id: 1789, name: "Walt Disney Japan" },
  { id: 417, name: "Walt Disney Studios" },
  { id: 2089, name: "Wan Wei Mao Donghua" },
  { id: 318, name: "WAO World" },
  { id: 1537, name: "Wargaming Japan" },
  { id: 415, name: "Warner Bros. Japan" },
  { id: 1889, name: "Warner Bros. Pictures" },
  { id: 1011, name: "Warner Music Japan" },
  { id: 2343, name: "WarRock" },
  { id: 1920, name: "Watermark" },
  { id: 1772, name: "Wawayu Animation" },
  { id: 2070, name: "Wei Chuang Jiang Xin" },
  { id: 1954, name: "Welz Animation Studios" },
  { id: 817, name: "WField" },
  { id: 1327, name: "White Bear" },
  { id: 314, name: "White Fox" },
  { id: 2032, name: "WHOPPERS" },
  { id: 2165, name: "Wicky.Records" },
  { id: 1596, name: "Will Palette" },
  { id: 2270, name: "Wise Guy" },
  { id: 858, name: "Wit Studio" },
  { id: 1970, name: "Wolf Smoke Studio" },
  { id: 2052, name: "Wolfsbane" },
  { id: 511, name: "Wonder Kids" },
  { id: 1648, name: "World Cosplay Summit" },
  { id: 33, name: "WOWOW" },
  { id: 2060, name: "Wulifang Digital" },
  { id: 2091, name: "Xanthus Media" },
  { id: 27, name: "Xebec" },
  { id: 2257, name: "XEBEC M2" },
  { id: 1572, name: "XFLAG" },
  { id: 1573, name: "XFLAG Pictures" },
  { id: 1578, name: "Xing" },
  { id: 2206, name: "Xuni Yinxiang Gongzuo Shi" },
  { id: 2096, name: "Y&amp;N Brothers" },
  { id: 239, name: "Y.O.U.C" },
  { id: 795, name: "Yahoo! Japan" },
  { id: 2132, name: "Yamaha Music Communications" },
  { id: 1055, name: "Yamamura Animation, Inc." },
  { id: 1833, name: "Yamasa" },
  { id: 381, name: "Yamato Works" },
  { id: 1431, name: "Yaoqi" },
  { id: 1560, name: "Yaoyorozu" },
  { id: 308, name: "Yellow Film" },
  { id: 1958, name: "YHKT Entertainment" },
  { id: 2194, name: "Yi Chen Animation" },
  { id: 1665, name: "Yili Animation Studio" },
  { id: 1687, name: "Yokohama Animation Lab" },
  { id: 127, name: "Yomiko Advertising" },
  { id: 675, name: "Yomiuri Advertising" },
  { id: 1792, name: "Yomiuri Shimbun" },
  { id: 76, name: "Yomiuri Telecasting" },
  { id: 1492, name: "Yomiuri TV Enterprise" },
  { id: 2011, name: "Yonago Gainax" },
  { id: 1453, name: "Yoon's Color" },
  { id: 1820, name: "Yoshimoto Creative Agency" },
  { id: 2009, name: "Yostar Pictures" },
  { id: 220, name: "Youmex" },
  { id: 236, name: "YTV" },
  { id: 1678, name: "Yuhodo" },
  { id: 2112, name: "YUKE'S" },
  { id: 1749, name: "Yumearu" },
  { id: 96, name: "Yumeta Company" },
  { id: 1392, name: "Zack Promotion" },
  { id: 1930, name: "Zelico Film" },
  { id: 1081, name: "ZERO-A" },
  { id: 1379, name: "Zero-G" },
  { id: 1131, name: "Zero-G Room" },
  { id: 218, name: "Zexcs" },
  { id: 2230, name: "Zipang" },
  { id: 1245, name: "ZIZ Entertainment (ZIZ)" },
  { id: 1376, name: "ZOOM ENTERPRISE" },
  { id: 557, name: "Zyc" },
];
